using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.DTO.Proyecciones
{
    public class CifrasPrincipalesDTO
    {
              public string UImporteMes1 {get;set;}
              public string UImporteMes2 {get;set;}
              public string UImporteMes3 {get;set;}
              public string UImporteMes4 {get;set;}
              public string UImporteMes5 {get;set;}
              public string UImporteMes6 {get;set;}
              public string UImporteMes7 {get;set;}
              public string UImporteMes8 {get;set;}
              public string UImporteMes9 {get;set;}
              public string UImporteMes10 {get;set;}
              public string UImporteMes11 {get;set;}
              public string UImporteMes12 {get;set;}
              public string UsVentasMes1 {get;set;}
              public string UsVentasMes2 {get;set;}
              public string UsVentasMes3 {get;set;}
              public string UsVentasMes4 {get;set;}
              public string UsVentasMes5 {get;set;}
              public string UsVentasMes6 {get;set;}
              public string UsVentasMes7 {get;set;}
              public string UsVentasMes8 {get;set;}
              public string UsVentasMes9 {get;set;}
              public string UsVentasMes10 {get;set;}
              public string UsVentasMes11 {get;set;}
              public string UsVentasMes12 {get;set;}
              public string UtilidadITotal {get;set;}
              public string UtilidadVTotal {get;set;}
              public string UtilidadOperacionIMes1 {get;set;}
              public string UtilidadOperacionIMes2 {get;set;}
              public string UtilidadOperacionIMes3 {get;set;}
              public string UtilidadOperacionIMes4 {get;set;}
              public string UtilidadOperacionIMes5 {get;set;}
              public string UtilidadOperacionIMes6 {get;set;}
              public string UtilidadOperacionIMes7 {get;set;}
              public string UtilidadOperacionIMes8 {get;set;}
              public string UtilidadOperacionIMes9 {get;set;}
              public string UtilidadOperacionIMes10 {get;set;}
              public string UtilidadOperacionIMes11 {get;set;}
              public string UtilidadOperacionIMes12 {get;set;}
              public string UtilidadOperacionVMes1 {get;set;}
              public string UtilidadOperacionVMes2 {get;set;}
              public string UtilidadOperacionVMes3 {get;set;}
              public string UtilidadOperacionVMes4 {get;set;}
              public string UtilidadOperacionVMes5 {get;set;}
              public string UtilidadOperacionVMes6 {get;set;}
              public string UtilidadOperacionVMes7 {get;set;}
              public string UtilidadOperacionVMes8 {get;set;}
              public string UtilidadOperacionVMes9 {get;set;}
              public string UtilidadOperacionVMes10 {get;set;}
              public string UtilidadOperacionVMes11 {get;set;}
              public string UtilidadOperacionVMes12 {get;set;}
              public string UAcumuladaMes1 {get;set;}
              public string UAcumuladaMes2 {get;set;}
              public string UAcumuladaMes3 {get;set;}
              public string UAcumuladaMes4 {get;set;}
              public string UAcumuladaMes5 {get;set;}
              public string UAcumuladaMes6 {get;set;}
              public string UAcumuladaMes7 {get;set;}
              public string UAcumuladaMes8 {get;set;}
              public string UAcumuladaMes9 {get;set;}
              public string UAcumuladaMes10 {get;set;}
              public string UAcumuladaMes11 {get;set;}
              public string UAcumuladaMes12 {get;set;}
              public string UMensualMes1 {get;set;}
              public string UMensualMes2 {get;set;}
              public string UMensualMes3 {get;set;}
              public string UMensualMes4 {get;set;}
              public string UMensualMes5 {get;set;}
              public string UMensualMes6 {get;set;}
              public string UMensualMes7 {get;set;}
              public string UMensualMes8 {get;set;}
              public string UMensualMes9 {get;set;}
              public string UMensualMes10 {get;set;}
              public string UMensualMes11 {get;set;}
              public string UMensualMes12 {get;set;}
              public string UMargeVentas1 {get;set;}
              public string UMargeVentas2 {get;set;}
              public string UMargeVentas3 {get;set;}
              public string UMargeVentas4 {get;set;}
              public string UMargeVentas5 {get;set;}
              public string UMargeVentas6 {get;set;}
              public string UMargeVentas7 {get;set;}
              public string UMargeVentas8 {get;set;}
              public string UMargeVentas9 {get;set;}
              public string UMargeVentas10 {get;set;}
              public string UMargeVentas11 {get;set;}
              public string UMargeVentas12 {get;set;}
              public string VAcumuladaMes1 {get;set;}
              public string VAcumuladaMes2 {get;set;}
              public string VAcumuladaMes3 {get;set;}
              public string VAcumuladaMes4 {get;set;}
              public string VAcumuladaMes5 {get;set;}
              public string VAcumuladaMes6 {get;set;}
              public string VAcumuladaMes7 {get;set;}
              public string VAcumuladaMes8 {get;set;}
              public string VAcumuladaMes9 {get;set;}
              public string VAcumuladaMes10 {get;set;}
              public string VAcumuladaMes11 {get;set;}
              public string VAcumuladaMes12 {get;set;}
              public string VMensualMes1 {get;set;}
              public string VMensualMes2 {get;set;}
              public string VMensualMes3 {get;set;}
              public string VMensualMes4 {get;set;}
              public string VMensualMes5 {get;set;}
              public string VMensualMes6 {get;set;}
              public string VMensualMes7 {get;set;}
              public string VMensualMes8 {get;set;}
              public string VMensualMes9 {get;set;}
              public string VMensualMes10 {get;set;}
              public string VMensualMes11 {get;set;}
              public string VMensualMes12 {get;set;}
              public string GOAcumuladaMes1 {get;set;}
              public string GOAcumuladaMes2 {get;set;}
              public string GOAcumuladaMes3 {get;set;}
              public string GOAcumuladaMes4 {get;set;}
              public string GOAcumuladaMes5 {get;set;}
              public string GOAcumuladaMes6 {get;set;}
              public string GOAcumuladaMes7 {get;set;}
              public string GOAcumuladaMes8 {get;set;}
              public string GOAcumuladaMes9 {get;set;}
              public string GOAcumuladaMes10 {get;set;}
              public string GOAcumuladaMes11 {get;set;}
              public string GOAcumuladaMes12 {get;set;}
              public string GOMensualMes1 {get;set;}
              public string GOMensualMes2 {get;set;}
              public string GOMensualMes3 {get;set;}
              public string GOMensualMes4 {get;set;}
              public string GOMensualMes5 {get;set;}
              public string GOMensualMes6 {get;set;}
              public string GOMensualMes7 {get;set;}
              public string GOMensualMes8 {get;set;}
              public string GOMensualMes9 {get;set;}
              public string GOMensualMes10 {get;set;}
              public string GOMensualMes11 {get;set;}
              public string GOMensualMes12 {get;set;}
              public string GOMargenVentasMes1 {get;set;}
              public string GOMargenVentasMes2 {get;set;}
              public string GOMargenVentasMes3 {get;set;}
              public string GOMargenVentasMes4 {get;set;}
              public string GOMargenVentasMes5 {get;set;}
              public string GOMargenVentasMes6 {get;set;}
              public string GOMargenVentasMes7 {get;set;}
              public string GOMargenVentasMes8 {get;set;}
              public string GOMargenVentasMes9 {get;set;}
              public string GOMargenVentasMes10 {get;set;}
              public string GOMargenVentasMes11 {get;set;}
              public string GOMargenVentasMes12 {get;set;}
              public string FMMes1 {get;set;}
              public string FMMes2 {get;set;}
              public string FMMes3 {get;set;}
              public string FMMes4 {get;set;}
              public string FMMes5 {get;set;}
              public string FMMes6 {get;set;}
              public string FMMes7 {get;set;}
              public string FMMes8 {get;set;}
              public string FMMes9 {get;set;}
              public string FMMes10 {get;set;}
              public string FMMes11 {get;set;}
              public string FMMes12 {get;set;}
    }
}
