using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.Entity.Maquinaria.SOS
{
    public class MinadoEntity
    {
        public int id { get; set; }
        public string Signum_Account_No { get; set; }
        public string Name { get; set; }
        public string IMO_No { get; set; }
        public string Facility { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string Signum_Number { get; set; }
        public string Unit_ID { get; set; }
        public string Description { get; set; }
        public string Code { get; set; }
        public string Application { get; set; }
        public string Registered_Lubricant { get; set; }
        public string Location { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string Sample_Point_Status { get; set; }
        public string Licensee { get; set; }
        public string Service_Type { get; set; }
        public string Component_Type { get; set; }
        public string Target_PC_4 { get; set; }
        public string Target_PC_6 { get; set; }
        public string Target_PC_14 { get; set; }
        public string Fuel_Type { get; set; }
        public string RPM { get; set; }
        public string Cycles { get; set; }
        public string Pressure { get; set; }
        public string kW_Rating { get; set; }
        public string Coolant_Type { get; set; }
        public string Coolant_Brand { get; set; }
        public string Cylinder_Number { get; set; }
        public string Sample_ID { get; set; }
        public DateTime Date_Sampled { get; set; }
        public string Date_Received { get; set; }
        public DateTime Date_Reported { get; set; }
        public string Date_Landed { get; set; }
        public string Port_Landed { get; set; }
        public string Sampling_Point { get; set; }
        public string Sampling_Point_Other { get; set; }
        public string Signum_Service { get; set; }
        public string Lubricant_Tested { get; set; }
        public string Equipment_Age { get; set; }
        public string Equipment_UOM { get; set; }
        public string Oil_Age { get; set; }
        public string Oil_Age_UOM { get; set; }
        public string Oil_Age_UOM_Status { get; set; }
        public string Total_Engine_Hours { get; set; }
        public string Oil_Service_Hours { get; set; }
        public string Oil_Volume { get; set; }
        public string Oil_Volume_UOM { get; set; }
        public string Makeup_Volume { get; set; }
        public string MakeUp_Volume_UOM { get; set; }
        public string Oil_Changed { get; set; }
        public string Filter_Changed { get; set; }
        public string Oil_Temp_In { get; set; }
        public string Oil_Temp_Out { get; set; }
        public string Oil_Temp_UOM { get; set; }
        public string Coolant_Temp_In { get; set; }
        public string Coolant_Temp_Out { get; set; }
        public string Coolant_Temp_UOM { get; set; }
        public string Reservoir_Temp { get; set; }
        public string Reservoir_Temp_UOM { get; set; }
        public string Reservoir_Temp_UOM_Status { get; set; }
        public string Ambient_Temp { get; set; }
        public string Ambient_Temp_Status { get; set; }
        public string Relative_Humidity { get; set; }
        public string Oil_Used_24_Hrs { get; set; }
        public string Oil_Used_24_Hrs_UOM { get; set; }
        public string Oil_Used_24_Hrs_UOM_Status { get; set; }
        public string kW_at_Sampling { get; set; }
        public string kW_at_Sampling_Status { get; set; }
        public string Feed_Rate_l_cyd_day { get; set; }
        public string Feed_Rate_l_cyd_day_Status { get; set; }
        public string Contamination_Rating { get; set; }
        public string Contamination_Rating_Status { get; set; }
        public string Equipment_Rating { get; set; }
        public string Equipment_Rating_Status { get; set; }
        public string Oil_Rating { get; set; }
        public string Oil_Rating_Status { get; set; }
        public string Overall_Status { get; set; }
        public string Sample_Result { get; set; }
        public string Sample_Result_Status { get; set; }
        public string Ag_Silver { get; set; }
        public string Ag_Silver_Status { get; set; }
        public string Air_Release { get; set; }
        public string Air_Release_Status { get; set; }
        public string Al_Aluminum { get; set; }
        public string Al_Aluminum_Status { get; set; }
        public string Alcohol_wt_P { get; set; }
        public string Alcohol_wt_P_Status { get; set; }
        public string Alkalinity_Reserve_wt_P { get; set; }
        public string Alkalinity_Reserve_wt_P_Status { get; set; }
        public string Antioxidant_wt_P { get; set; }
        public string Antioxidant_wt_P_Status { get; set; }
        public string Appearance { get; set; }
        public string Appearance_Status { get; set; }
        public string B__Boron { get; set; }
        public string B__Boron_Status { get; set; }
        public string Ba_Barium { get; set; }
        public string Ba_Barium_Status { get; set; }
        public string Ca_Calcium { get; set; }
        public string Ca_Calcium_Status { get; set; }
        public string Cd_Cadmium { get; set; }
        public string Cd_Cadmium_Status { get; set; }
        public string Cl_Chlorine__Xray { get; set; }
        public string Cl_Chlorine__Xray_Status { get; set; }
        public string Compatibility { get; set; }
        public string Compatibility_Status { get; set; }
        public string Coolant_Indicator { get; set; }
        public string Coolant_Indicator_Status { get; set; }
        public string Cr_Chromium { get; set; }
        public string Cr_Chromium_Status { get; set; }
        public string Cu_Copper { get; set; }
        public string Cu_Copper_Status { get; set; }
        public string DAC__P_Asphaltines { get; set; }
        public string DAC__P_Asphaltines_Status { get; set; }
        public string Demul__a_54C { get; set; }
        public string Demul__a_54C_Status { get; set; }
        public string Ester_wt_P { get; set; }
        public string Ester_wt_P_Status { get; set; }
        public string Fe_Iron { get; set; }
        public string Fe_Iron_Status { get; set; }
        public string Flash_Point_COC { get; set; }
        public string Flash_Point_COC_Status { get; set; }
        public string Flash_Point_PM { get; set; }
        public string Flash_Point_PM_Status { get; set; }
        public string Flash_Point_SETA { get; set; }
        public string Flash_Point_SETA_Status { get; set; }
        public string Foam_Seq_1 { get; set; }
        public string Foam_Seq_1_Status { get; set; }
        public string Fuel_Dilut_Vol_P { get; set; }
        public string Fuel_Dilut_Vol_P_Status { get; set; }
        public string _P_Fuel_Sulfur { get; set; }
        public string _P_Fuel_Sulfur_Status { get; set; }
        public string Initial_pH { get; set; }
        public string Initial_pH_Status { get; set; }
        public string Insolubles_5u { get; set; }
        public string Insolubles_5u_Status { get; set; }
        public string ISO_Code_4_6_14 { get; set; }
        public string ISO_Code_4_6_14_Status { get; set; }
        public string K_Potassium { get; set; }
        public string K_Potassium_Status { get; set; }
        public string MCR { get; set; }
        public string MCR_Status { get; set; }
        public string Mg__Magnesium { get; set; }
        public string Mg__Magnesium_Status { get; set; }
        public string Mg_Magnesium { get; set; }
        public string Mg_Magnesium_Status { get; set; }
        public string Mo_Molybdenum { get; set; }
        public string Mo_Molybdenum_Status { get; set; }
        public string Na_Sodium { get; set; }
        public string Na_Sodium_Status { get; set; }
        public string Ni_Nickel { get; set; }
        public string Ni_Nickel_Status { get; set; }
        public string Nitration_Ab_cm { get; set; }
        public string Nitration_Ab_cm_Status { get; set; }
        public string Nitration_Tendency { get; set; }
        public string Nitration_Tendency_Status { get; set; }
        public string Nitrocmpnds_Ab_cm { get; set; }
        public string Nitrocmpnds_Ab_cm_Status { get; set; }
        public string Oxidation_Ab_cm { get; set; }
        public string Oxidation_Ab_cm_Status { get; set; }
        public string Oxidation_Tendency { get; set; }
        public string Oxidation_Tendency_Status { get; set; }
        public string P__Phosphorus { get; set; }
        public string P__Phosphorus_Status { get; set; }
        public string P_Phosphorus { get; set; }
        public string P_Phosphorus_Status { get; set; }
        public string Particle_Count_14u { get; set; }
        public string Particle_Count_14u_Status { get; set; }
        public string Particle_Count_4u { get; set; }
        public string Particle_Count_4u_Status { get; set; }
        public string Particle_Count_6u { get; set; }
        public string Particle_Count_6u_Status { get; set; }
        public string Pb_Lead { get; set; }
        public string Pb_Lead_Status { get; set; }
        public string pH { get; set; }
        public string pH_Status { get; set; }
        public string PQ__Index { get; set; }
        public string PQ__Index_Status { get; set; }
        public string RBOT_Min { get; set; }
        public string RBOT_Min_Status { get; set; }
        public string SAN { get; set; }
        public string SAN_Status { get; set; }
        public string Si_Silicon { get; set; }
        public string Si_Silicon_Status { get; set; }
        public string Sn_Tin { get; set; }
        public string Sn_Tin_Status { get; set; }
        public string Soot_Wt_P { get; set; }
        public string Soot_Wt_P_Status { get; set; }
        public string TAN_mg_KOH_gm { get; set; }
        public string TAN_mg_KOH_gm_Status { get; set; }
        public string TBN_mg_KOH_gm_ { get; set; }
        public string TBN_mg_KOH_gm__Status { get; set; }
        public string TBN_mg_KOH_gm { get; set; }
        public string TBN_mg_KOH_gm_Status { get; set; }
        public string Ti_Titanium { get; set; }
        public string Ti_Titanium_Status { get; set; }
        public string Ultra_Centrifuge_Rating { get; set; }
        public string Ultra_Centrifuge_Rating_Status { get; set; }
        public string V_Vanadium { get; set; }
        public string V_Vanadium_Status { get; set; }
        public string Viscosity__a_100C { get; set; }
        public string Viscosity__a_100C_Status { get; set; }
        public string Viscosity__a_40C { get; set; }
        public string Viscosity__a_40C_Status { get; set; }
        public string Viscosity_Grade { get; set; }
        public string Viscosity_Grade_Status { get; set; }
        public string Water_Hot_Plate { get; set; }
        public string Water_Hot_Plate_Status { get; set; }
        public string Water_Vol__P { get; set; }
        public string Water_Vol__P_Status { get; set; }
        public string Water_Vol_P { get; set; }
        public string Water_Vol_P_Status { get; set; }
        public string Zn__Zinc { get; set; }
        public string Zn__Zinc_Status { get; set; }
        public string Zn_Zinc { get; set; }
        public string Comments { get; set; }
        public string Comments_Status { get; set; }
        public string Demul_a54C_Oil_Water_Emul_Time { get; set; }
        public string Demul_a54C_Oil_Water_Emul_Time_Status { get; set; }
        public string Demul_a54C_min { get; set; }
        public string Demul_a54C_min_Status { get; set; }
        public string Particle_Count_Diluted_4um { get; set; }
        public string Particle_Count_Diluted_4um_Status { get; set; }
        public string Particle_Count_Diluted_6um { get; set; }
        public string Particle_Count_Diluted_6um_Status { get; set; }
        public string Particle_Count_Diluted_14um { get; set; }
        public string Particle_Count_Diluted_14um_Status { get; set; }
        public string Diluted_ISO_Code_4_6_14 { get; set; }
        public string Diluted_ISO_Code_4_6_14_Status { get; set; }
        public string Mn_Manganese { get; set; }
    }
}
