echo "Copying .NET 4.7 DLL"
echo "======================================="

COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\Cloud\WebForms.Cloud\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\Miscellaneous\Image Gallery\ImageGallery\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\Miscellaneous\Keyword Search\Keyword.PdfSearch\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\Miscellaneous\Large Document\LargeDocument\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\Miscellaneous\PdfJs Export\Doconut.Viewer.PdfJs\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\MVC\Annotations\AnnDoconutViewer\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\MVC\Lean\LeanViewer\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\MVC\Multiple\MultipleDoconutViewer\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\MVC\Search\OCR\DoconutViewerSearch\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\MVC\Search\Simple\PdfSearch\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\MVC\Simple\DoconutViewer\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\MVC\WebFarm\Annotations\WebFarmAnnDoconutViewer\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\MVC\WebFarm\Search\WebFarmSearch\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\MVC\WebFarm\Simple\WebFarmDocViewer\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\WebForms\Minimal\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\WebForms\Full\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\Websites\DocumentViewer-2010\Bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\Websites\DocumentViewer-2019\Bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\Websites\Minimal\bin"
COPY "Bin\Asp.Net Framework 4.7\*.dll" "Samples\NET Framework 4.7\WinForms\PdfExport\bin"

echo "Copying License File"
echo "======================================="

COPY "License\Doconut.lic" "Samples\NET Framework 4.7\Cloud\WebForms.Cloud\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\Miscellaneous\Image Gallery\ImageGallery\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\Miscellaneous\Keyword Search\Keyword.PdfSearch\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\Miscellaneous\Large Document\LargeDocument\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\Miscellaneous\PdfJs Export\Doconut.Viewer.PdfJs\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\MVC\Annotations\AnnDoconutViewer\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\MVC\Lean\LeanViewer\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\MVC\Multiple\MultipleDoconutViewer\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\MVC\Search\OCR\DoconutViewerSearch\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\MVC\Search\Simple\PdfSearch\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\MVC\Simple\DoconutViewer\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\MVC\WebFarm\Annotations\WebFarmAnnDoconutViewer\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\MVC\WebFarm\Search\WebFarmSearch\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\MVC\WebFarm\Simple\WebFarmDocViewer\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\WebForms\Minimal\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\WebForms\Full\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\Websites\DocumentViewer-2010\Bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\Websites\DocumentViewer-2019\Bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\Websites\Minimal\bin"
COPY "License\Doconut.lic" "Samples\NET Framework 4.7\WinForms\PdfExport\bin"

echo "Copying .NET Core DLL"
echo "======================================="

COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET 6.0\MVC\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\Angular\Doconut.Angular\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\Blazor\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\Cloud\Core.Cloud\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\Docker\Doconut.Docker.Core\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\Miscellaneous\Acrobat Pdf Theme\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\Miscellaneous\Ppt Slideshow\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\MVC\Doconut.Annotation.Core\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\MVC\Doconut.Mvc.Core\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\MVC\Doconut.Ocr.Search.Core\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\MVC\Doconut.Pdf.Search.Core\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\Razor Pages\DoconutRazorWebApp\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\Cloud\Core.Cloud.AWS.S3\bin"
COPY "Bin\NET Standard 2.0 (.Net Core)\*.dll" "Samples\NET Core\Cloud\Core.Cloud.Azure\bin"

echo "Copying License File"
echo "======================================="

COPY "License\Doconut.lic" "Samples\NET 6.0\MVC\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\Angular\Doconut.Angular\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\Blazor\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\Cloud\Core.Cloud\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\Docker\Doconut.Docker.Core\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\Miscellaneous\Acrobat Pdf Theme\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\Miscellaneous\Ppt Slideshow\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\MVC\Doconut.Annotation.Core\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\MVC\Doconut.Mvc.Core\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\MVC\Doconut.Ocr.Search.Core\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\MVC\Doconut.Pdf.Search.Core\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\Razor Pages\DoconutRazorWebApp\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\Cloud\Core.Cloud.AWS.S3\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core\Cloud\Core.Cloud.Azure\wwwroot"

echo "Copying .NET Core Non Windows Platforms DLL"
echo "======================================="

COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET 6.0 Non Windows Platforms\MVC\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\Angular\Doconut.Angular\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\Blazor\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\Cloud\Core.Cloud\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\Docker\Doconut.Docker.Core\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\Miscellaneous\Acrobat Pdf Theme\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\Miscellaneous\Ppt Slideshow\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\MVC\Doconut.Annotation.Core\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\MVC\Doconut.Mvc.Core\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\MVC\Doconut.Ocr.Search.Core\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\MVC\Doconut.Pdf.Search.Core\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\Razor Pages\DoconutRazorWebApp\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\Cloud\Core.Cloud.AWS.S3\bin"
COPY "Bin\NET Standard 2.0 (.Net Core) Non Windows Platforms\*.dll" "Samples\NET Core Non Windows Platforms\Cloud\Core.Cloud.Azure\bin"


echo "Copying License File Non Windows Platforms"
echo "======================================="

COPY "License\Doconut.lic" "Samples\NET 6.0 Non Windows Platforms\MVC\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\Angular\Doconut.Angular\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\Blazor\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\Cloud\Core.Cloud\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\Docker\Doconut.Docker.Core\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\Miscellaneous\Acrobat Pdf Theme\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\Miscellaneous\Ppt Slideshow\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\MVC\Doconut.Annotation.Core\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\MVC\Doconut.Mvc.Core\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\MVC\Doconut.Ocr.Search.Core\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\MVC\Doconut.Pdf.Search.Core\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\Razor Pages\DoconutRazorWebApp\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\Cloud\Core.Cloud.AWS.S3\wwwroot"
COPY "License\Doconut.lic" "Samples\NET Core Non Windows Platforms\Cloud\Core.Cloud.Azure\wwwroot"