using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.DTO.CuentasPorCobrar
{
    public class cxcMovClientesDTO
    {
        public int id { get; set; }
        public int numcte { get; set; }
        public int factura { get; set; }
        public DateTime? fecha { get; set; }
        public int tm { get; set; }
        public DateTime? fechavenc { get; set; }
        public string concepto { get; set; }
        public string cc { get; set; }
        public string referenciaoc { get; set; }
        public decimal monto { get; set; }
        public decimal tipocambio { get; set; }
        public decimal? iva { get; set; }
        public int year { get; set; }
        public int mes { get; set; }
        public int poliza { get; set; }
        public string tp { get; set; }
        public int? linea { get; set; }
        public string generado { get; set; }
        public string es_factura { get; set; }
        public string moneda { get; set; }
        public string autorizapago { get; set; }
        public decimal? total { get; set; }
        public string bit_escrituracion { get; set; }
        public string poliza_generada { get; set; }
        public string acumula_ingresos { get; set; }
        public string tipo_clase { get; set; }
        public int? num_factura_moratorio { get; set; }
        public string origen { get; set; }
        public decimal? porcent_iva { get; set; }
        public int? folio_imp { get; set; }
        public int? linea_imp { get; set; }
        public string bit_orden_escr { get; set; }
        public decimal? descuentos { get; set; }
        public string cfd_serie { get; set; }
        public int? cfd_folio { get; set; }
        public DateTime? cfd_fecha { get; set; }
        public string cfd_certificado { get; set; }
        public int? cfd_ano_aprob { get; set; }
        public int? cfd_num_aprob { get; set; }
        public string cfd_cadena_original { get; set; }
        public string cfd_certificado_sello { get; set; }
        public string cfd_sello_digital { get; set; }
        public DateTime? fecha_cancelacion { get; set; }
        public int? usuario_cancela { get; set; }
        public decimal? total_canc { get; set; }
        public decimal? iva_canc { get; set; }
        public decimal? monto_canc { get; set; }
        public string cfd_forma_pago { get; set; }
        public string cfd_cond_pago { get; set; }
        public decimal? cfd_porc_iva { get; set; }
        public string cfd_ruta_pdf { get; set; }
        public string cfd_ruta_xml { get; set; }
        public string cfd_no_certificado { get; set; }
        public decimal? cfd_monto { get; set; }
        public decimal? cfd_iva { get; set; }
        public decimal? cfd_total { get; set; }
        public string UUID { get; set; }
        public string cfd_mn { get; set; }
        public string cfd_enviada { get; set; }
        public string cfd_regimen_fiscal { get; set; }
        public string cfd_sucursal { get; set; }
        public string cfd_metodo_pago { get; set; }
        public string cfd_num_cta_pago { get; set; }
        public string bit_cfdi { get; set; }
        public string fecha_timbrado { get; set; }
        public string certificado_sat { get; set; }
        public string sello_sat { get; set; }
        public string comentarios_sat { get; set; }
        public string refid { get; set; }
        public int? insumo { get; set; }
        public string folio_canc_stf { get; set; }
        public string numregidtrib { get; set; }
        public DateTime? fecha_registro { get; set; }
        public string concepto_CFDI { get; set; }
        public string observaciones_cfdi { get; set; }
        public int? bit_stf { get; set; }
        public int? folio_parcial { get; set; }
        //public string copia_xml { get; set; }
        //public string copia_xml_pdf { get; set; }
        public string rfcemisorctaord { get; set; }
        public string RfcEmisorCtaBen { get; set; }
        public string nombancoordext { get; set; }
        public string CtaOrdenante { get; set; }
        public string CtaBeneficiario { get; set; }
        public decimal? impsaldoant { get; set; }
        public decimal? imppagado { get; set; }
        public decimal? impsaldoinsoluto { get; set; }
        public decimal? reg_fiscal_sat { get; set; }
        public string cfd_tiporelacion { get; set; }
        public string tipocadpago { get; set; }
        public string condicionespago { get; set; }
        public string usocfdi { get; set; }
        public string cfd_metodo_pago_sat { get; set; }
        public string cfd_forma_pago_sat { get; set; }
        public string cfd_condicionespago { get; set; }
        public string cfd_version { get; set; }
        public string sello_digital_pago { get; set; }
        public string cadena_original_pago { get; set; }
        public int? no_parcialidades { get; set; }
        public int? parcialidades { get; set; }
        public string cia_global { get; set; }
        public string anticipo { get; set; }
        public string pago_anticipo { get; set; }
        public string cancelacion_anticipo { get; set; }
        public string ClaveProdServ { get; set; }
        public string claveunidadsat { get; set; }
        public int? insumo_EK { get; set; }
        public string desglosa_iva_anticipo { get; set; }
        public string relacionado_escrituracion { get; set; }
        public int? numcte_rel_canc { get; set; }
        public int? factura_rel_canc { get; set; }
        public int? tm_rel_canc { get; set; }
        public int? fecha_rel_canc { get; set; }
        public DateTime? fecha_registro_rel_canc { get; set; }
        public int? numcte_rel { get; set; }
        public string factura_rel { get; set; }
        public int? tm_rel { get; set; }
        public DateTime? fecha_rel { get; set; }
        public DateTime? fecha_registro_rel { get; set; }
        public string descuenta_anticipo { get; set; }
        public string folio_canc_anticipo { get; set; }
        public string cfd_concepto_egreso { get; set; }
        public string pago_cfdi_escrituracion { get; set; }
        public int? cfdirel { get; set; }
        public int? tmcfdirel { get; set; }
        public string cfd_predial_enc { get; set; }
        public int? id_complemento { get; set; }
        public string tipoagrupacion { get; set; }
        public string referenceidentificacion { get; set; }
        public int? ordencompra_addenda { get; set; }
        public int? determinante_addenda { get; set; }
        public string pedido { get; set; }
        public int? contrarecibo { get; set; }
        public int? idpac { get; set; }
        public string formato_addenda { get; set; }
        public string nomunidad_addenda { get; set; }
        public string noproyecto_addenda { get; set; }
        public int? foliorecibo_addenda { get; set; }
        public DateTime? fecha_pago_Real { get; set; }
        public string iddocumento { get; set; }
        public string NumOperacion { get; set; }
        public string Bancoext { get; set; }
        public string CertPago { get; set; }
        public string CadPago { get; set; }
        public string SelloPago { get; set; }
        public decimal? tipocambio_pago { get; set; }
        public string moneda_pago { get; set; }
        public int? monto_pago { get; set; }
        public string activa_factoraje { get; set; }
        public int? id_factoraje { get; set; }
        public string cfd_estatus_cancelacion { get; set; }
        public string cfd_estado { get; set; }
        public int? cfd_movto_cancela { get; set; }
        public string cfd_tipocomprobante { get; set; }
        public int? cfd_cancelado { get; set; }

        //Extra
        public string ccDesc { get; set; }
        public string nombreCliente { get; set; }
    }
}
