using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Core.DTO.Administracion.Seguridad.SaludOcupacional
{
    public class HistorialClinicoDTO
    {
        public int id { get; set; }
        public string folio { get; set; }
        public int dtsPer_EmpresaID { get; set; }
        public int dtsPer_CCID { get; set; }
        public string dtsPer_Paciente { get; set; }
        public DateTime? dtsPer_FechaHora { get; set; }
        public DateTime? dtsPer_FechaNac { get; set; }
        public string dtsPer_Sexo { get; set; }
        public int dtsPer_EstadoCivilID { get; set; }
        public int dtsPer_TipoSangreID { get; set; }
        public string dtsPer_CURP { get; set; }
        public string dtsPer_Domicilio { get; set; }
        public string dtsPer_Ciudad { get; set; }
        public int dtsPer_EscolaridadID { get; set; }
        public string dtsPer_LugarNac { get; set; }
        public string dtsPer_Telefono { get; set; }
        public bool motEva_esIngreso { get; set; }
        public bool motEva_esRetiro { get; set; }
        public bool motEva_esEvaOpcional { get; set; }
        public bool motEva_esPostIncapacidad { get; set; }
        public bool motEva_esReubicacion { get; set; }
        public string antLab_Puesto { get; set; }
        public string antLab_Empresa { get; set; }
        public string antLab_Desde { get; set; }
        public string antLab_Hasta { get; set; }
        public string antLab_Turno { get; set; }
        public bool antLab_esDePie { get; set; }
        public bool antLab_esInclinado { get; set; }
        public bool antLab_esSentado { get; set; }
        public bool antLab_esArrodillado { get; set; }
        public bool antLab_esCaminando { get; set; }
        public bool antLab_esOtra { get; set; }
        public string antLab_Cual { get; set; }
        public string accET_Empresa { get; set; }
        public string accET_Anio { get; set; }
        public string accET_LesionAreaAnatomica { get; set; }
        public string accET_Secuelas { get; set; }
        public string accET_Cuales { get; set; }
        public string accET_ExamNoAceptables { get; set; }
        public string accET_Causas { get; set; }
        public string accET_AbandonoTrabajo { get; set; }
        public string accET_IncapacidadFrecuente { get; set; }
        public string accET_Prolongadas { get; set; }
        public bool usoElePP_esActual { get; set; }
        public bool usoElePP_esCasco { get; set; }
        public bool usoElePP_esTapaboca { get; set; }
        public bool usoElePP_esGafas { get; set; }
        public bool usoElePP_esRespirador { get; set; }
        public bool usoElePP_esBotas { get; set; }
        public bool usoElePP_esAuditivos { get; set; }
        public bool usoElePP_esOverol { get; set; }
        public bool usoElePP_esGuantes { get; set; }
        public string usoElePP_OtroCual { get; set; }
        public string usoElePP_DeberiaRecibir { get; set; }
        public string usoElePP_ConsideraAdecuado { get; set; }
        public string antFam_esTuberculosis { get; set; }
        public string antFam_TuberculosisParentesco { get; set; }
        public string antFam_esHTA { get; set; }
        public string antFam_HTAParentesco { get; set; }
        public string antFam_esDiabetes { get; set; }
        public string antFam_DiabetesParentesco { get; set; }
        public string antFam_esACV { get; set; }
        public string antFam_ACVParentesco { get; set; }
        public string antFam_esInfarto { get; set; }
        public string antFam_InfartoParentesco { get; set; }
        public string antFam_esAsma { get; set; }
        public string antFam_AsmaParentesco { get; set; }
        public string antFam_esAlergias { get; set; }
        public string antFam_AlergiasParentesco { get; set; }
        public string antFam_esMental { get; set; }
        public string antFam_MentalParentesco { get; set; }
        public string antFam_esCancer { get; set; }
        public string antFam_CancerParentesco { get; set; }
        public string antFam_Observaciones { get; set; }
        public string antPerNoPat_Tabaquismo { get; set; }
        public string antPerNoPat_CigarroDia { get; set; }
        public string antPerNoPat_CigarroAnios { get; set; }
        public string antPerNoPat_Alcoholismo { get; set; }
        public string antPerNoPat_AlcoholismoAnios { get; set; }
        public bool antPerNoPat_esDrogadiccion { get; set; }
        public bool antPerNoPat_esMarihuana { get; set; }
        public bool antPerNoPat_esCocaina { get; set; }
        public bool antPerNoPat_esAnfetaminas { get; set; }
        public string antPerNoPat_Otros { get; set; }
        public string antPerNoPat_Inmunizaciones { get; set; }
        public string antPerNoPat_Tetanicos { get; set; }
        public DateTime? antPerNoPat_FechaAntitetanica { get; set; }
        public string antPerNoPat_Hepatitis { get; set; }
        public string antPerNoPat_Influenza { get; set; }
        public DateTime? antPerNoPat_FechaInfluenza { get; set; }
        public string antPerNoPat_Infancia { get; set; }
        public string antPerNoPat_DescInfancia { get; set; }
        public string antPerNoPat_Alimentacion { get; set; }
        public string antPerNoPat_Higiene { get; set; }
        public string antPerNoPat_MedicacionActual { get; set; }
        public bool antPerPat_esNeoplasicos { get; set; }
        public bool antPerPat_esNeumopatias { get; set; }
        public bool antPerPat_esAsma { get; set; }
        public bool antPerPat_esFimico { get; set; }
        public bool antPerPat_esNeumoconiosis { get; set; }
        public bool antPerPat_esCardiopatias { get; set; }
        public bool antPerPat_esReumaticos { get; set; }
        public bool antPerPat_esAlergias { get; set; }
        public bool antPerPat_esHipertension { get; set; }
        public bool antPerPat_esHepatitis { get; set; }
        public bool antPerPat_esTifoidea { get; set; }
        public bool antPerPat_esHernias { get; set; }
        public bool antPerPat_esLumbalgias { get; set; }
        public bool antPerPat_esDiabetes { get; set; }
        public bool antPerPat_esEpilepsias { get; set; }
        public bool antPerPat_esVenereas { get; set; }
        public bool antPerPat_esCirugias { get; set; }
        public bool antPerPat_esFracturas { get; set; }
        public string antPerPat_ObservacionesPat { get; set; }
        public bool intApaSis_esRespiratorio { get; set; }
        public bool intApaSis_esDigestivo { get; set; }
        public bool intApaSis_esCardiovascular { get; set; }
        public bool intApaSis_esNervioso { get; set; }
        public bool intApaSis_esUrinario { get; set; }
        public bool intApaSis_esEndocrino { get; set; }
        public bool intApaSis_esPsiquiatrico { get; set; }
        public bool intApaSis_esEsqueletico { get; set; }
        public bool intApaSis_esAudicion { get; set; }
        public bool intApaSis_esVision { get; set; }
        public bool intApaSis_esOlfato { get; set; }
        public bool intApaSis_esTacto { get; set; }
        public string intApaSis_ObservacionesPat { get; set; }
        public string padAct_PadActuales { get; set; }
        public string expFSV_TArterial { get; set; }
        public string expFSV_Pulso { get; set; }
        public string expFSV_Temp { get; set; }
        public string expFSV_FCardiaca { get; set; }
        public string expFSV_FResp { get; set; }
        public string expFSV_Peso { get; set; }
        public string expFSV_Talla { get; set; }
        public string expFSV_IMC { get; set; }
        public string expFC_Craneo { get; set; }
        public string expFC_Parpados { get; set; }
        public string expFC_Conjutiva { get; set; }
        public string expFC_Reflejos { get; set; }
        public string expFC_FosasNasales { get; set; }
        public string expFC_Boca { get; set; }
        public string expFC_Amigdalas { get; set; }
        public string expFC_Dentadura { get; set; }
        public string expFC_Encias { get; set; }
        public string expFC_Cuello { get; set; }
        public string expFC_Tiroides { get; set; }
        public string expFC_Ganglios { get; set; }
        public string expFC_Oidos { get; set; }
        public string expFC_Otros { get; set; }
        public string expFC_Observaciones { get; set; }
        public string expFAV_VisCerAmbosOjos { get; set; }
        public string expFAV_VisCerOjoIzq { get; set; }
        public string expFAV_VisCerOjoDer { get; set; }
        public string expFAV_VisLejAmbosOjos { get; set; }
        public string expFAV_VisLejOjoIzq { get; set; }
        public string expFAV_VisLejOjoDer { get; set; }
        public string expFAV_CorregidaAmbosOjos { get; set; }
        public string expFAV_CorregidaOjoIzq { get; set; }
        public string expFAV_CorregidaOjoDer { get; set; }
        public string expFAV_CampimetriaOI { get; set; }
        public string expFAV_CampimetriaOD { get; set; }
        public string expFAV_PterigionOI { get; set; }
        public string expFAV_PterigionOD { get; set; }
        public string expFAV_FondoOjo { get; set; }
        public string expFAV_Daltonismo { get; set; }
        public string expFAV_Observaciones { get; set; }
        public bool expFTATE_esCamposPulmonares { get; set; }
        public bool expFTATE_esPuntosDolorosos { get; set; }
        public bool expFTATE_esGenitales { get; set; }
        public bool expFTATE_esRuidosCardiacos { get; set; }
        public bool expFTATE_esHallusValgus { get; set; }
        public bool expFTATE_esHerniasUmbili { get; set; }
        public bool expFTATE_esAreaRenal { get; set; }
        public bool expFTATE_esVaricocele { get; set; }
        public bool expFTATE_esGrandulasMamarias { get; set; }
        public bool expFTATE_esColumnaVertebral { get; set; }
        public bool expFTATE_esPiePlano { get; set; }
        public bool expFTATE_esVarices { get; set; }
        public bool expFTATE_esMiembrosSup { get; set; }
        public bool expFTATE_esParedAbdominal { get; set; }
        public bool expFTATE_esAnillosInguinales { get; set; }
        public bool expFTATE_esMiembrosInf { get; set; }
        public bool expFTATE_esTatuajes { get; set; }
        public bool expFTATE_esVisceromegalias { get; set; }
        public bool expFTATE_esMarcha { get; set; }
        public bool expFTATE_esHerniasInguinales { get; set; }
        public bool expFTATE_esHombrosDolorosos { get; set; }
        public bool expFTATE_esQuistes { get; set; }
        public string expFTATE_Observaciones { get; set; }
        public bool expFTATE_MS_HombroDer_esFlexion { get; set; }
        public bool expFTATE_MS_HombroIzq_esFlexion { get; set; }
        public bool expFTATE_MS_CodoDer_esFlexion { get; set; }
        public bool expFTATE_MS_CodoIzq_esFlexion { get; set; }
        public bool expFTATE_MS_MunecaDer_esFlexion { get; set; }
        public bool expFTATE_MS_MunecaIzq_esFlexion { get; set; }
        public bool expFTATE_MS_DedosDer_esFlexion { get; set; }
        public bool expFTATE_MS_DedosIzq_esFlexion { get; set; }
        public bool expFTATE_MS_HombroDer_esExtension { get; set; }
        public bool expFTATE_MS_HombroIzq_esExtension { get; set; }
        public bool expFTATE_MS_CodoDer_esExtension { get; set; }
        public bool expFTATE_MS_CodoIzq_esExtension { get; set; }
        public bool expFTATE_MS_MunecaDer_esExtension { get; set; }
        public bool expFTATE_MS_MunecaIzq_esExtension { get; set; }
        public bool expFTATE_MS_DedosDer_esExtension { get; set; }
        public bool expFTATE_MS_DedosIzq_esExtension { get; set; }
        public bool expFTATE_MS_HombroDer_esAbduccion { get; set; }
        public bool expFTATE_MS_HombroIzq_esAbduccion { get; set; }
        public bool expFTATE_MS_CodoDer_esAbduccion { get; set; }
        public bool expFTATE_MS_CodoIzq_esAbduccion { get; set; }
        public bool expFTATE_MS_MunecaDer_esAbduccion { get; set; }
        public bool expFTATE_MS_MunecaIzq_esAbduccion { get; set; }
        public bool expFTATE_MS_DedosDer_esAbduccion { get; set; }
        public bool expFTATE_MS_DedosIzq_esAbduccion { get; set; }
        public bool expFTATE_MS_HombroDer_esAduccion { get; set; }
        public bool expFTATE_MS_HombroIzq_esAduccion { get; set; }
        public bool expFTATE_MS_MunecaDer_esAduccion { get; set; }
        public bool expFTATE_MS_MunecaIzq_esAduccion { get; set; }
        public bool expFTATE_MS_DedosDer_esAduccion { get; set; }
        public bool expFTATE_MS_DedosIzq_esAduccion { get; set; }
        public bool expFTATE_MS_HombroDer_esRotInterna { get; set; }
        public bool expFTATE_MS_HombroIzq_esRotInterna { get; set; }
        public bool expFTATE_MS_MunecaDer_esRotInterna { get; set; }
        public bool expFTATE_MS_MunecaIzq_esRotInterna { get; set; }
        public bool expFTATE_MS_DedosDer_esRotInterna { get; set; }
        public bool expFTATE_MS_DedosIzq_esRotInterna { get; set; }
        public bool expFTATE_MS_HombroDer_esRotExterna { get; set; }
        public bool expFTATE_MS_HombroIzq_esRotExterna { get; set; }
        public bool expFTATE_MS_MunecaDer_esRotExterna { get; set; }
        public bool expFTATE_MS_MunecaIzq_esRotExterna { get; set; }
        public bool expFTATE_MS_DedosDer_esRotExterna { get; set; }
        public bool expFTATE_MS_DedosIzq_esRotExterna { get; set; }
        public bool expFTATE_MS_CodoDer_esPronacion { get; set; }
        public bool expFTATE_MS_CodoIzq_esPronacion { get; set; }
        public bool expFTATE_MS_MunecaDer_esPronacion { get; set; }
        public bool expFTATE_MS_MunecaIzq_esPronacion { get; set; }
        public bool expFTATE_MS_CodoDer_esSupinacion { get; set; }
        public bool expFTATE_MS_CodoIzq_esSupinacion { get; set; }
        public bool expFTATE_MS_MunecaDer_esSupinacion { get; set; }
        public bool expFTATE_MS_MunecaIzq_esSupinacion { get; set; }
        public bool expFTATE_MS_MunecaDer_esDesvUlnar { get; set; }
        public bool expFTATE_MS_MunecaIzq_esDesvUlnar { get; set; }
        public bool expFTATE_MS_MunecaDer_esDesvRadial { get; set; }
        public bool expFTATE_MS_MunecaIzq_esDesvRadial { get; set; }
        public bool expFTATE_MS_MunecaDer_esOponencia { get; set; }
        public bool expFTATE_MS_MunecaIzq_esOponencia { get; set; }
        public bool expFTATE_MS_DedosDer_esOponencia { get; set; }
        public bool expFTATE_MS_DedosIzq_esOponencia { get; set; }
        public bool expFTATE_MI_CaderaDer_esFlexion { get; set; }
        public bool expFTATE_MI_CaderaIzq_esFlexion { get; set; }
        public bool expFTATE_MI_RodillasDer_esFlexion { get; set; }
        public bool expFTATE_MI_RodillasIzq_esFlexion { get; set; }
        public bool expFTATE_MI_CllPieDer_esFlexion { get; set; }
        public bool expFTATE_MI_CllPieIzq_esFlexion { get; set; }
        public bool expFTATE_MI_DedosDer_esFlexion { get; set; }
        public bool expFTATE_MI_DedosIzq_esFlexion { get; set; }
        public bool expFTATE_MI_CaderaDer_esExtension { get; set; }
        public bool expFTATE_MI_CaderaIzq_esExtension { get; set; }
        public bool expFTATE_MI_RodillasDer_esExtension { get; set; }
        public bool expFTATE_MI_RodillasIzq_esExtension { get; set; }
        public bool expFTATE_MI_CllPieDer_esExtension { get; set; }
        public bool expFTATE_MI_CllPieIzq_esExtension { get; set; }
        public bool expFTATE_MI_DedosDer_esExtension { get; set; }
        public bool expFTATE_MI_DedosIzq_esExtension { get; set; }
        public bool expFTATE_MI_CaderaDer_esAbduccion { get; set; }
        public bool expFTATE_MI_CaderaIzq_esAbduccion { get; set; }
        public bool expFTATE_MI_CllPieDer_esAbduccion { get; set; }
        public bool expFTATE_MI_CllPieIzq_esAbduccion { get; set; }
        public bool expFTATE_MI_DedosDer_esAbduccion { get; set; }
        public bool expFTATE_MI_DedosIzq_esAbduccion { get; set; }
        public bool expFTATE_MI_CaderaDer_esAduccion { get; set; }
        public bool expFTATE_MI_CaderaIzq_esAduccion { get; set; }
        public bool expFTATE_MI_CllPieDer_esAduccion { get; set; }
        public bool expFTATE_MI_CllPieIzq_esAduccion { get; set; }
        public bool expFTATE_MI_DedosDer_esAduccion { get; set; }
        public bool expFTATE_MI_DedosIzq_esAduccion { get; set; }
        public bool expFTATE_MI_CaderaDer_esRotInterna { get; set; }
        public bool expFTATE_MI_CaderaIzq_esRotInterna { get; set; }
        public bool expFTATE_MI_RodillasDer_esRotInterna { get; set; }
        public bool expFTATE_MI_RodillasIzq_esRotInterna { get; set; }
        public bool expFTATE_MI_CllPieDer_esRotInterna { get; set; }
        public bool expFTATE_MI_CllPieIzq_esRotInterna { get; set; }
        public bool expFTATE_MI_CaderaDer_esRotExterna { get; set; }
        public bool expFTATE_MI_CaderaIzq_esRotExterna { get; set; }
        public bool expFTATE_MI_RodillasDer_esRotExterna { get; set; }
        public bool expFTATE_MI_RodillasIzq_esRotExterna { get; set; }
        public bool expFTATE_MI_CllPieDer_esRotExterna { get; set; }
        public bool expFTATE_MI_CllPieIzq_esRotExterna { get; set; }
        public bool expFTATE_MI_CllPieDer_esInversion { get; set; }
        public bool expFTATE_MI_CllPieIzq_esInversion { get; set; }
        public bool expFTATE_MI_CllPieDer_esEversion { get; set; }
        public bool expFTATE_MI_CllPieIzq_esEversion { get; set; }
        public string expFTATE_MS_MI_Observaciones { get; set; }
        public string expFDT_PielMucosas { get; set; }
        public string expFDT_EstadoPsiquiatrico { get; set; }
        public string expFDT_ExamenNeurologico { get; set; }
        public string expFDT_FobiasActuales { get; set; }
        public string expFDT_Higiene { get; set; }
        public string expFDT_ConstitucionFisica { get; set; }
        public string expFDT_Otros { get; set; }
        public string expFDT_Observaciones { get; set; }
        public int estGab_TipoSanguineoID { get; set; }
        public string estGab_Antidoping { get; set; }
        public string estGab_Laboratorios { get; set; }
        public string estGab_ObservacionesGrupoRH { get; set; }
        public string estGab_ExamGenOrina { get; set; }
        public string estGab_ExamGenOrinaObservaciones { get; set; }
        public string estGab_Radiografias { get; set; }
        public string estGab_RadiografiasObservaciones { get; set; }
        public string estGab_Audiometria { get; set; }
        public string estGab_HBC { get; set; }
        public string estGab_AudiometriaObservaciones { get; set; }
        public string estGab_Espirometria { get; set; }
        public string estGab_EspirometriaObservaciones { get; set; }
        public string estGab_Electrocardiograma { get; set; }
        public string estGab_ElectrocardiogramaObservaciones { get; set; }
        public string estGab_FechaPrimeraDosis { get; set; }
        public string estGab_FechaSegundaDosis { get; set; }
        public int estGab_MarcaDosisID { get; set; }
        public string estGab_VacunacionObservaciones { get; set; }
        public string estGab_LstProblemas { get; set; }
        public string estGab_Recomendaciones { get; set; }
        public string esp_Espirometria { get; set; }
        public string esp_EspirometriaObservaciones { get; set; }
        public string aud_HipoacusiaOD { get; set; }
        public string aud_HipoacusiaOI { get; set; }
        public string aud_HBC { get; set; }
        public string aud_Diagnostico { get; set; }
        public string aud_KH1 { get; set; }
        public string aud_KH1_OI { get; set; }
        public string aud_KH1_OD { get; set; }
        public string aud_KH2 { get; set; }
        public string aud_KH2_OI { get; set; }
        public string aud_KH2_OD { get; set; }
        public string aud_KH3 { get; set; }
        public string aud_KH3_OI { get; set; }
        public string aud_KH3_OD { get; set; }
        public string aud_KH4 { get; set; }
        public string aud_KH4_OI { get; set; }
        public string aud_KH4_OD { get; set; }
        public string aud_KH5 { get; set; }
        public string aud_KH5_OI { get; set; }
        public string aud_KH5_OD { get; set; }
        public string aud_KH6 { get; set; }
        public string aud_KH6_OI { get; set; }
        public string aud_KH6_OD { get; set; }
        public string aud_KH7 { get; set; }
        public string aud_KH7_OI { get; set; }
        public string aud_KH7_OD { get; set; }
        public string aud_NotasAudiometria { get; set; }
        public string eleDer_Interpretacion { get; set; }
        public string radTCLP_Conclusiones { get; set; }
        public string certMed_CertificadoMedico { get; set; }
        public int certMed_AptitudID { get; set; }
        public DateTime? certMed_Fecha { get; set; }
        public string certMed_NombrePaciente { get; set; }
        public string recom_Recomendaciones { get; set; }
        public int medicoCreacionID { get; set; }
        public int? medicoModificacionID { get; set; }
        public int? cp_idUsuarioMedicoCP { get; set; }
        public string cp_observacionMedicoCP { get; set; }
        public int? cp_aptitudIDCP { get; set; }
        public int? cp_esVoBo { get; set; }
        public string cp_StrEsVoBo { get; set; }
        public int idUsuarioCreacion { get; set; }
        public int idUsuarioModificacion { get; set; }
        public DateTime? fechaCreacion { get; set; }
        public DateTime? fechaModificacion { get; set; }
        public bool registroActivo { get; set; }
    }
}